"""Freeze sender inputs from the exact payload and query available at generation.

Later receiver drift is a separate input to the surface inequality, never a
feature used to regenerate the transmitted surface for the same payload/query.
"""

from __future__ import annotations

import hashlib
from dataclasses import asdict, dataclass

from bces.data.objects import ObjectMessage
from bces.models.batch import ModelBatchRow, build_model_batch_row
from bces.protocol.bindings import sender_id_hash
from bces.protocol.query import ReceiverQuery
from bces.utils.hashing import canonical_json_hash


@dataclass(frozen=True)
class FrozenReferenceInput:
    batch: ModelBatchRow
    payload_sha256: str
    query_sha256: str
    feature_sha256: str
    generated_at_ms: int
    query_available_at_ms: int
    context_available_at_ms: int
    message_timestamp_ms: int
    query_provenance: str

    def to_dict(self) -> dict:
        return asdict(self)


def freeze_reference_input(
    message: ObjectMessage,
    query: ReceiverQuery,
    *,
    generated_at_ms: int,
    query_available_at_ms: int,
    context_available_at_ms: int,
    query_provenance: str,
    occlusion_proxy: float,
    estimated_delay_s: float,
    map_context_flags: int = 0,
) -> FrozenReferenceInput:
    """Use the 32×10 object representation and the 12-point intended path.

    Provenance must identify a received query or a query generated by the frozen
    reference policy using past/current inputs. A future observed path cannot
    stand in for the intended query path. Adapters must audit this provenance.
    """
    times = (generated_at_ms, query_available_at_ms, context_available_at_ms)
    if any(type(value) is not int or value < 0 for value in times):
        raise ValueError("availability timestamps must be non-negative integers")
    if max(query_available_at_ms, context_available_at_ms, message.timestamp_ms) > generated_at_ms:
        raise ValueError("sender features contain information unavailable at generation")
    if query.reference_state.timestamp_ms > query_available_at_ms:
        raise ValueError("query reference state is later than query availability")
    if query_provenance not in {"received_query", "frozen_reference_policy"}:
        raise ValueError("query must not be derived from a future observed trajectory")
    if sender_id_hash(message.sender_id) != query.expected_sender_id_hash:
        raise ValueError("message sender does not match the query")
    batch = build_model_batch_row(
        message, query, occlusion_proxy=occlusion_proxy,
        estimated_delay_s=estimated_delay_s, map_context_flags=map_context_flags,
    )
    return FrozenReferenceInput(
        batch=batch,
        payload_sha256=hashlib.sha256(message.encode()).hexdigest(),
        query_sha256=canonical_json_hash(asdict(query)),
        feature_sha256=canonical_json_hash(asdict(batch)),
        generated_at_ms=generated_at_ms,
        query_available_at_ms=query_available_at_ms,
        context_available_at_ms=context_available_at_ms,
        message_timestamp_ms=message.timestamp_ms,
        query_provenance=query_provenance,
    )
